name: graduation_project
description: "A Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flare_flutter: ^3.0.2
  flutter_animation_progress_bar: ^2.3.1
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  lottie: ^3.1.2
  onboarding: ^4.0.2
  pin_code_fields: ^8.0.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/preview.png"
  min_sdk_android: 21
  flutter_lints: ^4.0.0


flutter:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/fonts/

  uses-material-design: true

  fonts:
    - family: font001
      fonts:
        - asset: assets/fonts/inter.ttf

    - family: font002
      fonts:
        - asset: assets/fonts/courgette.ttf

    - family: font003
      fonts:
        - asset: assets/fonts/JotiOne-Regular.ttf